# Generated by Django 4.2 on 2024-09-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="articles/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("1", "정치"),
                    ("2", "경제"),
                    ("3", "사회"),
                    ("4", "생활/문화"),
                    ("5", "세계"),
                    ("6", "IT/과학"),
                ],
                max_length=1,
                unique=True,
            ),
        ),
    ]
