# Generated by Django 4.2 on 2024-09-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_like"),
        ("articles", "0007_comment_user"),
    ]

    operations = []
